version: "3.8"

services:
  mafia-client:
    image: sjw7324/mafia-client:latest
    container_name: mafia-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_network:
    external: true
